mysite/accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/', views.signup, name='signup'), 
    url(r'^login/', views.loginview, name='login'), 
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
import rhymes.views
from django.conf.urls import url

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', rhymes.views.index, name="index"),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^rhymes/', include('rhymes.urls')),
    url(r'^parent/', rhymes.views.parent, name="parent"),
] 

mysite/rhymes/urls.py
from django.urls import path
from . import views
from django.conf.urls import url

urlpatterns = [
    url(r'comprehension', views.comprehension, name='comprehension'), 
    url(r'math', views.math, name='math'), 
    url(r'parent', views.parent, name='parent'), 
    url(r'colourgames', views.colourgames, name='colourgames'),
    url(r'index', views.index, name='index'),
]

mysite/accounts/models.py
from django.db import models

# Create your models here.

mysite/accounts/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User

def signup(request):
	if request.method == 'POST':
		if request.POST['password1'] == request.POST['password2']:
			try:
				# checking is username already exists
				user = User.objects.get(username=request.POST['username'])
				return render(request, 'accounts/signup.html', {'error': 'This username has already been taken'})
			except User.DoesNotExist:
				# logging in as the user
				user = User.objects.create_user(request.POST['username'], password=request.POST['password1'])
				login(request, user)
				return render(request, 'accounts/login.html')

		else:
			return render(request, 'accounts/signup.html', {'error': 'Passwords did not match'})

	else:
		return render(request, 'accounts/signup.html')

# how to log a user in : documentation
def loginview(request):
	if request.method == 'POST':
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(request, username=username, password=password)
		if user is not None:
			login(request, user)
			return render(request, 'rhymes/home.html', {'error': 'Logged in successfully'})
		else:
			return render(request, 'accounts/login.html', {'error': 'Invalid username/password. Try again.'})
	else:
		return render(request, 'accounts/login.html')

mysite/rhymes/views.py
from django.shortcuts import render
from django.http import HttpResponse

def comprehension(request):
    return render(request, 'rhymes/mine.html')

def home(request):
    return render(request, 'rhymes/home.html')

def math(request):
    return render(request, 'rhymes/math.html')

def parent(request):
    return render(request, 'rhymes/parent.html')

def colourgames(request):
	return render(request,'rhymes/game.html')

def index(request):
	return render(request,'rhymes/index.html')

mysite/accounts/templates/accounts/login.html
{% load static %}

<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="{% static 'css/signup.css' %}">

<div class="container" style="color: red">
	<h1>Log In!</h1>

{% if error %}
{{ error }}
{% endif %}

<form method="POST" style="color: blue" action="{% url 'accounts:login' %}">
	{% csrf_token %}
	<h3>Username</h3>
	<input type="text" name="username">
	<h3>Password</h3>
	<input type="password" name="password"><br><br>
	<input type="submit" value="Login">
</form>
</div>

mysite/accounts/templates/accounts/signup.html
{% load static %}
<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="{% static 'css/signup.css' %}">
<div class = "vertical-center">

<div class="container" style="color: red, background-color:pink">
<h1>Sign Up!</h1>

{% if error %}
{{ error }}
{% endif %}


<form method="POST" style="color: blue" action="{% url 'accounts:signup' %}">
	{% csrf_token %}
	<h3>Username</h3>
	<input type="text" name="username">
	<h3>Password</h3>
	<input type="password" name="password1">
	<h3>Confirm Password</h3>
	<input type="password" name="password2">
	<h3>Child's Name</h3>
	<input type="text" name="c_name">
	<h3>Child's Age</h3>
	<input type="number" name="c_age"><br><br>
	<input type="submit" value="Sign Up">
</form>

</div>
</div>

mysite/rhymes/templates/rhymes/game.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    {% load static %}
    <meta charset="utf-8">
    <title>Thomas and Colours</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/game.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Indie+Flower|ZCOOL+KuaiLe" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Indie+Flower|Pacifico|ZCOOL+KuaiLe" rel="stylesheet">
  </head>
  <body>
    <div class="container">

        <h1 id="see"align='center'>Select Pictures containing Red</h1>
        <p></p>
        <p></p>
        <p></p>

      <table id="tab" align ='center'>
        <tr>
          <td> <img id="one"src="https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Strawberries.jpg/1200px-Strawberries.jpg" alt="LOADING IMAGE" width="190" height="190"></td>
          <td ><img id="two"src="https://ae01.alicdn.com/kf/HTB1GEBwbjfguuRjy1zeq6z0KFXaS/1pcs-Doraemon-Nobi-Nobita-Toy-figure-Nobita-Pvc-Action-Figures-Toys-15cm-Box-Packaged-Retail-Free.jpg_640x640.jpg" alt="LOADING IMAGE" width="190" height="190"></td>
          <td><img id="three"src="https://static.independent.co.uk/s3fs-public/styles/story_medium/public/indy100/bkxLRrwYqgW/25426-1yh1bw8.jpg" alt="LOADING IMAGE" width="190" height="190"></td>
        </tr>

        <tr>
          <td><img id="four"src="https://www.bourncreative.com/wp-content/uploads/2010/10/black.jpg" alt="LOADING IMAGE" width="190" height="190"></td>
          <td><img id="five"src="https://images-na.ssl-images-amazon.com/images/I/61iQ1ph8o4L._SL1000_.jpg" alt="LOADING IMAGE" width="190" height="190"></td>
          <td><img id="six"src="https://cdn1.vectorstock.com/i/1000x1000/56/25/star-icon-yellow-sign-object-vector-24495625.jpg" alt="LOADING IMAGE" width="190" height="190"></td>
        </tr>

        <tr>
          <td><img id="seven"src="https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Bob_the_Builder_ride%2C_Sainsbury%27s_north_London.jpg/789px-Bob_the_Builder_ride%2C_Sainsbury%27s_north_London.jpg" alt="LOADING IMAGE" width="190" height="190"></td>
          <td><img id="eight"src="http://www.vespa.in/images/ourchoice/Vespa_red_banner101.png" alt="LOADING IMAGE" width="190" height="190"></td>
          <td><img id="nine"src="https://images-na.ssl-images-amazon.com/images/I/71lnQdxlWzL._SX466_.jpg" alt="LOADING IMAGE" width="190" height="190"></td>
        </tr>

      </table>

     <p></p>
     <p></p>
     <p></p>
     <p></p>
     <div id="d"class="text-center"><button class="btn btn-primary btn-lg" type="button">Get Marks!</button></div>

    </div>
    <script src = "{% static 'js/game.js' %}">

    </script>

  <h1 id="fo" align='center'>Your Marks: <span id="myText"></span></h1>

  </body>
</html>

mysite/rhymes/templates/rhymes/home.html
<!DOCTYPE html>
<html>
<head>
	{% load static %}
	<title>kickstart</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css" integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous">

	<link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}">

</head>
<body style="background-image: url(https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=667&q=80);" >

<nav class="navbar navbar-expand-sm bg-success navbar-dark">
  <div class="container-fluid">
    <div class="navbar-header"><p class="navbar-brand"  style="font-weight: bold; color: yellow">Study Buddy<span class="glyphicon glyphicon-education"></span></p> 
    </div>
    
   
    
    <div class="btn-group">
  <!-- <button type="button" href="/parent" class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"  style="border-width: 3px; border-color: yellow; color: yellow; font-size: 20px">
    Parent
  </button> -->
  <a class="btn btn-warning" href="/parent" role="button">Parent</a>
  <!-- <div class="dropdown-menu">
    <a class="dropdown-item" href="/accounts/signup">SignUp</a>
    <div class="dropdown-divider"></div>
    <a class="dropdown-item" href="/accounts/login">Login</a>
  </div> -->
</div>
  </div>
</nav>
<div class="container">
<h2>I am Thomas! Your Study Buddy!</h2>
<a class="btn btn-primary" href="/rhymes/comprehension" role="button">Thomas and Words</a>
<a class="btn btn-primary" href="/rhymes/colourgames">Thomas and Colours</a>

<a class="btn btn-primary" href="/rhymes/math" role="button">Thomas and Math</a>
</div>
</body>
</html>

mysite/rhymes/templates/rhymes/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Home</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
  <link href="https://fonts.googleapis.com/css?family=Indie+Flower" rel="stylesheet">
  <style type="text/css">

body{background-image: url("https://images.unsplash.com/photo-1515437765356-882f1727ef38?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80") ;
background-size: cover;}

  </style>
</head>
<body>



<nav class="navbar navbar-expand-sm bg-success navbar-dark">
  <div class="container-fluid">
    <div class="navbar-header"><p class="navbar-brand"  style="font-weight: bold; color: yellow">Study Buddy<span class="glyphicon glyphicon-education"></span></p> 
    </div>
    
   
    
    <div class="btn-group">
  <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"  style="border-width: 3px; border-color: yellow; color: yellow; font-size: 20px">
    Parent
  </button>
  <div class="dropdown-menu">
    <a class="dropdown-item" href="/accounts/signup">SignUp</a>
    <div class="dropdown-divider"></div>
    <a class="dropdown-item" href="/accounts/login">Login</a>
  </div>
</div>
  </div>
</nav>
<div style="position: "><p style="font-family: 'Indie Flower', cursive; font-weight: bolder; padding-left: 20px; font-size: 20px">“Today you are You, that is truer than true. <br>There is no one alive who is Youer than You.”<br>
― Dr. Seuss</p>
</div>






  
</body>
</html>

mysite/rhymes/templates/rhymes/math.html
<!DOCTYPE html>
<html>
<head>
  {% load static %}
   <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Math_101</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/shoelace-css/1.0.0-beta16/shoelace.css">

	<link type="text/css" rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/math.css' %}">

</head>
<body >

<section id="hero">
      <div class="hero-container container">
      <h1>Thomas and Math</h1>
      <hr>
      <h2 style="color: #f4c842">Let Us Have Some Fun With Numbers!<br>Perform The Follwing Operations. Best Of Luck <span class="glyphicon glyphicon-thumbs-up"></span></h2>
      <div id="div1" style="font-weight: 900; font-size: 60px"></div>
                <div class="app"> 
                  <div class="input-single">
                    <textarea id="note-textarea" type="reset" placeholder="Answer" rows="1"></textarea>
                </div>   
                <button id="start-record-btn" title="Start Recording">Speak</button>
                <button  id="pause-record-btn" title="Pause Recording">Submit</button>
               
           

        </div>
        </div>
  </section>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        
        <script type="text/javascript" src="{% static 'js/math.js' %}"></script>
        <script src="{% static 'js/script.js' %}"></script>
        <!-- Only used for the demos ads. Please ignore and remove. --> 
      <!--   <script src="https://cdn.tutorialzine.com/misc/enhance/v3.js" async></script> -->
</body>
</html>

mysite/rhymes/templates/rhymes/mine.html
<!DOCTYPE html>
<html>
<head>
	<title>Thomas and Words</title>
    {% load static %}
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/shoelace-css/1.0.0-beta16/shoelace.css">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
	<div class="container">

            <h1>Thomas and His Words</h1>

            <div class="app"> 
                <h3>Comprehension Practice</h3>
                <button id="listen-comprehension" title="Start Listening">Listen</button>
                <div class="input-single">
                    <textarea id="note-textarea" type="reset" placeholder="Answer" rows="1"></textarea>
                </div>         
                <button id="bol-question" title="bolo question">Listen to Question</button>
                <button id="start-record-btn" title="Start Recording">Start Recognition</button>
                <button id="check-answer" title="check answer">Evaluate</button>
                <!-- <button id="pause-record-btn" title="Pause Recording">Pause Recognition</button> -->
<!--                 <button id="save-note-btn" title="Save Note">Save Note</button>    -->
                <!-- <p id="recording-instructions">Press the <strong>Start Recognition</strong> button and allow access.</p> -->
                
                

            </div>

        </div>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="{% static 'js/script.js' %}"></script>

        <!-- Only used for the demos ads. Please ignore and remove. --> 
        <!-- <script src="https://cdn.tutorialzine.com/misc/enhance/v3.js" async></script> -->
</body>
</html>

mysite/rhymes/templates/rhymes/parent.html
{% load static %}

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css" integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous">

<link rel="stylesheet" type="text/css" href="{% static 'css/parent.css' %}">

<h1 style="padding-left: 500px">
	Your Child's Progress 
</h1>

<span>
<img src="{% static 'pictures/mathphoto1.png' %}" class="img-responsive center-block" style='max-height: 200px; margin: 0 auto; display: table;'>	
</span>

<span>
<img src="{% static 'pictures/mathphoto2.png' %}" class="img-responsive center-block" style='max-height: 200px; margin: 0 auto; display: table;'>	
</span>

<span>
	<img src="{% static 'pictures/mathphoto3.png' %}" class="img-responsive center-block" style='max-height: 200px; margin: 0 auto; display: table;'>
</span>